{{- if .Values.microServices.vault -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  labels:
    service: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      service: vault
  template:
    metadata:
      labels:
        service: vault
    spec:
      initContainers:
      - name: volume-mount-hack
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /data"]
        volumeMounts:
        - name: data
          mountPath: /data
        resources:
          requests:
            memory: "32Mi"
            cpu: "0.1"
          limits:
            memory: "32Mi"
            cpu: "0.1"
        securityContext:
          runAsUser: 0
          runAsNonRoot: false
          readOnlyRootFilesystem: false
      containers:
        - name: vault
          image: hashicorp/vault:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8200
              protocol: TCP
          env:
            - name: VAULT_DEV_ROOT_TOKEN_ID
              value: {{ .Values.vault.TOKEN | quote }}
            - name: VAULT_ADDR
              value: "http://localhost:8200"
{{- end -}}