stages:
  - test
  - build
  - deploy

test:
  stage: test
  script:
    - echo "Hello world!"
  rules:
    - if: $CI_MERGE_REQUEST_ID

build:
  stage: build
  script:
    - echo "Building project..."

deploy:
  stage: deploy
  script:
    - echo "Deploying project..."
