stages:
  - scan
  - test
  - build
  - deploy

scan:
  stage: scan
  script:
    - echo "Hello world!"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

test:
  stage: test
  script:
    - echo "Hello world!"

build:
  stage: build
  script:
    - echo "Building project..."

deploy:
  stage: deploy
  script:
    - echo "Deploying project..."