stages:
  - scan
  - test
  - build
  - deploy

scan:
  image: aquasec/trivy:latest # Using the Trivy Docker image
  stage: scan
  script:
     - echo "Checking for new or modified YAML files..."
     - echo "finding defects in yaml file"
     - echo "display defect report"
     - echo "publish artifacts"
     - fail test
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

test:
  stage: test
  script:
    - echo "Hello world!"

build:
  stage: build
  script:
    - echo "Building project..."

deploy:
  stage: deploy
  script:
    - echo "Deploying project..."