stages:
  - test
  - build
  - deploy

test:
  stage: test
  script:
    - echo "Running tests..."

build:
  stage: build
  script:
    - echo "Building project..."

deploy:
  stage: deploy
  script:
    - echo "Deploying project..."
